name: Continuous integration

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - 1.41.0  # MSRV
        include:
          - rust: nightly
            experimental: true

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          #     target: thumbv7em-none-eabihf
          override: true
      - uses: actions-rs/cargo@v1
        with:
          # use-cross: true
          command: test
          args: --verbose
